package itcast.zz16.googleplay.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.File;

import itcast.zz16.googleplay.bean.AppInfo;
import itcast.zz16.googleplay.manager.DownloadManager;
import itcast.zz16.googleplay.utils.FileUtils;

/**
 * Entity mapped to table "DOWNLOAD_INFO".
 */
public class DownloadInfo {

    private Long id;
    private String appName;
    private Long appSize;
    private Long currentSize;
    private Integer downloadState;
    private String url;
    private String path;

    public DownloadInfo() {
    }

    public DownloadInfo(Long id) {
        this.id = id;
    }

    public DownloadInfo(Long id, String appName, Long appSize, Long currentSize, Integer downloadState, String url, String path) {
        this.id = id;
        this.appName = appName;
        this.appSize = appSize;
        this.currentSize = currentSize;
        this.downloadState = downloadState;
        this.url = url;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Long getAppSize() {
        return appSize;
    }

    public void setAppSize(Long appSize) {
        this.appSize = appSize;
    }

    public Long getCurrentSize() {
        return currentSize;
    }

    public void setCurrentSize(Long currentSize) {
        this.currentSize = currentSize;
    }

    public Integer getDownloadState() {
        return downloadState;
    }

    public void setDownloadState(Integer downloadState) {
        this.downloadState = downloadState;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }



    /*自动提供转换的方法*/
    public DownloadInfo clone(AppInfo appInfo){
        this.id = appInfo.id;
        this.appName = appInfo.name;
        this.appSize = appInfo.size;
        this.currentSize = 0l;
        this.downloadState = DownloadManager.STATE_NONE;
        this.url = appInfo.downloadUrl;
        this.path = FileUtils.getDowload().getAbsolutePath() + File.separator + appInfo.name + ".apk";
        return this;
    }

}
